services:
  mongodb:
    image: mongo:8.0
    container_name: project-ql-mongodb
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'try { rs.status() } catch (error) { rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"localhost:27017\"}]}) }' | mongosh --port 27017 --quiet",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    restart: unless-stopped

volumes:
  mongodb-data:
